source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://github.com/seongbrave/TwilightSpecs.git'   # 私有库
use_frameworks!

target 'Bella_Example' do
  pod 'Bella', :path => '../'

  target 'Bella_Tests' do
    inherit! :search_paths

    
  end
end
